baseurl = "/"
#baseurl = "https://example.org/"
languageCode = "it-it"
defaultContentLanguage = "it"
# defaultContentLanguageInSubdir = true
title = "Team Romagna Judo 2017"
#theme = "TRJ-theme"

#publishDir = "../dist"

contentDir = "content"
dataDir = "data"

relativeURLs = true
canonifyURLs = true

buildDrafts = false
buildFuture = false
buildExpired = false

archetypeDir = "archetypes"

#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
#googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 3
paginatePath = "page"
pluralizeListTitles = false

[blackfriday]
angledQuotes = true
#hrefTargetBlank = true

preserveTaxonomyNames = false
[taxonomies]

#  tag = "tags"
#  category = "categories"
#  series = "series"


# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
#disableKinds = ["taxonomy", "taxonomyTerm"]
#disableKinds = []

#sectionPagesMenu = "sections"

[permalinks]
#  post = "/:year/:month/:title/"


[mediaTypes]
#  [mediaTypes."text/enriched"]
#  suffix = "enr"
#  [mediaTypes."text/html"]
#  suffix = "asp"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]



[[menu.main]]
    name = "Corsi"
    url  = "corsi"
    identifier = "corsi"
#   pre = "template.HTML"
#   post = "template.HTML"
    weight = 1
#   parent = ""
#   children = "menu"

[[menu.main]]
    name = "Palestre"
    url  = "palestre"
    identifier = "palestre"
    weight = 2

#[[menu.main]]
#    name = "Gare"
#    url  = "gare"
#    identifier = "gare"
#    weight = 3
#
#[[menu.main]]
#    name = "Campus"
#    url  = "campus"
#    identifier = "campus"
#    weight = 4

[[menu.main]]
    name = "Notizie"
    url  = "notizie"
    identifier = "notizie"
	weight = 6

[[menu.main]]
    name = "Materiale"
    url  = "materiale"
    identifier = "materiale"
	weight = 7

[[menu.main]]
    name = "Album"
    url  = "album"
    identifier = "album"
	weight = 10



