baseurl = "/"
#baseurl = "https://example.org/"
languageCode = "it-it"
defaultContentLanguage = "it"
title = "Team Romagna Judo 2017"
theme = "hugo-strata-theme"

contentDir = "content"
dataDir = "data"

relativeURLs = true
canonifyURLs = true

buildDrafts = false
buildFuture = false
buildExpired = false

archetypeDir = "archetypes"

#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
#googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
pluralizeListTitles = false

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Team Romagna Judo"
	description = "Team Romagna Judo 1972"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
#		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
#		bio = "**I'm Strata**, a super simple<br> responsive site template freebie<br> crafted by [HTML5 UP](//html5up.net)."
		# The icons will be shown if you enter your username
#		twitter = "spf13"
#		github = "spf13"
#		gitlab = "spf13"
#		dribbble = ""
#		facebook = ""
#		googleplus = ""
#		flickr = ""
#		linkedin = ""

#		copyright = [
#			"&copy; John Doe",
#			"Design: [HTML5 UP](//html5up.net)",
#			"Demo Images: [Unsplash](//unsplash.com/)"
#		]


#	[params.about]
#		hide  = false
#		title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
#		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."
#
#
#	[params.portfolio]
#		hide  = false
#		title = "Recent Work"
#
#		[[params.portfolio.gallery]]
#			image = "fulls/01.jpg"
#			thumb = "thumbs/01.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."
#
#		[[params.portfolio.gallery]]
#			image = "fulls/02.jpg"
#			thumb = "thumbs/02.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."
#
#		[[params.portfolio.gallery]]
#			image = "fulls/03.jpg"
#			thumb = "thumbs/03.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."
#
#		[[params.portfolio.gallery]]
#			image = "fulls/04.jpg"
#			thumb = "thumbs/04.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."
#
#		[[params.portfolio.gallery]]
#			image = "fulls/05.jpg"
#			thumb = "thumbs/05.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."
#
#		[[params.portfolio.gallery]]
#			image = "fulls/06.jpg"
#			thumb = "thumbs/06.jpg"
#			title = "Lorem ipsum dolor."
#			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
#		title = "Get In Touch"
		title = "Contatti"
#		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."
		content = "Per contattarci, usate questo modulo."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "Team Romagna Judo, Lugo"
		address = [
			"Via Tomaso Emaldi, 20",
			"48022 Lugo",
			"Ravenna"
		]
		phone = "347 794 6028"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "teamromagnajudo1972@libero.it"
#		email = "teamromagnajudo1972@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "nome e cognome"
			email = "indirizzo email"
			message = "messagio"
			submit = "Invia il messaggio"


# Menu links that appear on the left sidebar
#[[menu.main]]
#	name = "Home"
#	url  = "/"
#	weight = 10

[[menu.main]]
    name = "Team"
    url  = "team"
    weight = 1

[[menu.main]]
    name = "Allenatori"
    url  = "allenatori"
    weight = 2

[[menu.main]]
    name = "Palestre"
    url  = "palestre"
    weight = 3

[[menu.main]]
	name = "Notizie"
	url  = "news"
	weight = 7

[[menu.main]]
	name = "Blog"
	url  = "post"
	weight = 10



