backend:
  name:   github
  repo:   teamromagnajudo1972/sito
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notizie"
    label: "Notizie"
    folder: "content/notizie"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout",                name: "layout",    widget: "hidden", default: "notizie"}
      - {label: "Menu",                  name: "menu",      widget: "hidden", default: "notizie"}
      - {label: "Titolo",                name: "title",     widget: "string"}
      - {label: "Data di pubblicazione", name: "date",      widget: "datetime"}
      - {label: "Featured Image",        name: "thumbnail", widget: "image"}
      - {label: "Body",                  name: "body",      widget: "markdown"}

  - name: "gare"
    label: "Gare"
    folder: "content/gare"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout",                name: "layout",    widget: "hidden", default: "gare"}
      - {label: "Menu",                  name: "menu",      widget: "hidden", default: "gare"}
      - {label: "Titolo",                name: "title",     widget: "string"}
      - {label: "Data della gara",       name: "date",      widget: "datetime"}
      - {label: "Luogo",                 name: "place",     widget: "string"}
      - {label: "Categorie",             name: "place",     widget: "string"}
      - {label: "Featured Image",        name: "thumbnail", widget: "image"}
#     - {label: "Rating (scale of 1-5)", name: "rating",    widget: "number"}
      - {label: "Body",                  name: "body",      widget: "markdown"}
#     - {label: "Language",              name: "language"}
#   filter:
#     field: language
#     value: it
