name = "TRJ-theme_v1"
license = "MIT"
description = "Design originale del sito Team Romagna Judo 1972 (layout v1)."
homepage = "https://www.teamromagnajudo.it/"
min_version = "0.101.0"

[author]
  name = "Team Romagna Judo 1972"
